/* Generated By:JJTree: Do not edit this line. WikiHeading.java */

package org.seasar.cms.wiki.parser;

public class WikiHeading extends SimpleNode {
  public WikiHeading(int id) {
    super(id);
  }

  public WikiHeading(WikiParser p, int id) {
    super(p, id);
  }

  public int level;
  public int num;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
