/* Generated By:JJTree: Do not edit this line. WikiFloatAlign.java */

package org.seasar.cms.wiki.parser;

public class WikiFloatAlign extends SimpleNode {
  public WikiFloatAlign(int id) {
    super(id);
  }

  public WikiFloatAlign(WikiParser p, int id) {
    super(p, id);
  }

  public String image;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
