/* Generated By:JJTree: Do not edit this line. WikiDefinedWord.java */

package org.seasar.cms.wiki.parser;

public class WikiDefinedWord extends SimpleNode {
  public WikiDefinedWord(int id) {
    super(id);
  }

  public WikiDefinedWord(WikiParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
