/* Generated By:JJTree: Do not edit this line. WikiInterwiki.java */

package org.seasar.cms.wiki.parser;

public class WikiInterwiki extends SimpleNode {
  public WikiInterwiki(int id) {
    super(id);
  }

  public WikiInterwiki(WikiParser p, int id) {
    super(p, id);
  }
  
  public String image;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
