/* Generated By:JJTree: Do not edit this line. WikiAnyOther.java */

package org.seasar.cms.wiki.parser;

public class WikiAnyOther extends SimpleNode {
  public WikiAnyOther(int id) {
    super(id);
  }

  public WikiAnyOther(WikiParser p, int id) {
    super(p, id);
  }

  public String letter;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
