/* Generated By:JJTree: Do not edit this line. c:\workspace3\cms-wiki\src\main\java\org\seasar\cms\wiki\parser\WikiParserVisitor.java */

package org.seasar.cms.wiki.parser;

public interface WikiParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(WikiSyntaxError node, Object data);
  public Object visit(WikiSkipToNewline node, Object data);
  public Object visit(WikiGenerateTree node, Object data);
  public Object visit(WikiParagraph node, Object data);
  public Object visit(WikiExcerpt node, Object data);
  public Object visit(WikiList node, Object data);
  public Object visit(WikiListMember node, Object data);
  public Object visit(WikiDefineList node, Object data);
  public Object visit(WikiDefinedWord node, Object data);
  public Object visit(WikiExplanationWord node, Object data);
  public Object visit(WikiPreshaped node, Object data);
  public Object visit(WikiTable node, Object data);
  public Object visit(WikiTablecolumn node, Object data);
  public Object visit(WikiTablemember node, Object data);
  public Object visit(WikiCSVTable node, Object data);
  public Object visit(WikiHeading node, Object data);
  public Object visit(WikiAlign node, Object data);
  public Object visit(WikiFloatAlign node, Object data);
  public Object visit(WikiHorizontalline node, Object data);
  public Object visit(WikiBlockPlugin node, Object data);
  public Object visit(WikiLetters node, Object data);
  public Object visit(WikiAnyOther node, Object data);
  public Object visit(WikiStrongItalic node, Object data);
  public Object visit(WikiDeleteline node, Object data);
  public Object visit(WikiAnnotation node, Object data);
  public Object visit(WikiInterwiki node, Object data);
  public Object visit(WikiLink node, Object data);
  public Object visit(WikiAlias node, Object data);
  public Object visit(WikiPagename node, Object data);
  public Object visit(WikiInlinePlugin node, Object data);
  public Object visit(WikiArgs node, Object data);
  public Object visit(WikiErrors node, Object data);
}
