/* Generated By:JJTree: Do not edit this line. WikiPreshaped.java */

package org.seasar.cms.wiki.parser;

public class WikiPreshaped extends SimpleNode {
  public WikiPreshaped(int id) {
    super(id);
  }

  public WikiPreshaped(WikiParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
