/* Generated By:JJTree: Do not edit this line. WikiTablecolumn.java */

package org.seasar.cms.wiki.parser;

public class WikiTablecolumn extends SimpleNode {
  public WikiTablecolumn(int id) {
    super(id);
  }

  public WikiTablecolumn(WikiParser p, int id) {
    super(p, id);
  }

  public boolean iscolspan = false;
  public boolean isrowspan = false;
  
  public String align;
  public String bgcolor;
  public String color;
  public String size;

  public int colspannum = 0;
  public int rowspannum = 0;
  
  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
