/* Generated By:JJTree: Do not edit this line. WikiCSVTable.java */

package org.seasar.cms.wiki.parser;

public class WikiCSVTable extends SimpleNode {
  public WikiCSVTable(int id) {
    super(id);
  }

  public WikiCSVTable(WikiParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
