/* Generated By:JJTree: Do not edit this line. WikiArgs.java */

package org.seasar.cms.wiki.parser;

public class WikiArgs extends SimpleNode {
  public WikiArgs(int id) {
    super(id);
  }

  public WikiArgs(WikiParser p, int id) {
    super(p, id);
  }

  public String[] args = null;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
