/* Generated By:JJTree: Do not edit this line. WikiSkipToNewline.java */

package org.seasar.cms.wiki.parser;

public class WikiSkipToNewline extends SimpleNode {
  public WikiSkipToNewline(int id) {
    super(id);
  }

  public WikiSkipToNewline(WikiParser p, int id) {
    super(p, id);
  }
  
  public String letter;

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
