/* Generated By:JJTree: Do not edit this line. WikiDeleteline.java */

package org.seasar.cms.wiki.parser;

public class WikiDeleteline extends SimpleNode {
  public WikiDeleteline(int id) {
    super(id);
  }

  public WikiDeleteline(WikiParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
