/* Generated By:JJTree: Do not edit this line. WikiHorizontalline.java */

package org.seasar.cms.wiki.parser;

public class WikiHorizontalline extends SimpleNode {
  public WikiHorizontalline(int id) {
    super(id);
  }

  public WikiHorizontalline(WikiParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
