/* Generated By:JJTree: Do not edit this line. WikiAnnotation.java */

package org.seasar.cms.wiki.parser;

public class WikiAnnotation extends SimpleNode {
  public WikiAnnotation(int id) {
    super(id);
  }

  public WikiAnnotation(WikiParser p, int id) {
    super(p, id);
  }

  public int num;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
