/* Generated By:JJTree: Do not edit this line. WikiGenerateTree.java */

package org.seasar.cms.wiki.parser;

import java.util.List;

public class WikiGenerateTree extends SimpleNode {
  public WikiGenerateTree(int id) {
    super(id);
  }

  public WikiGenerateTree(WikiParser p, int id) {
    super(p, id);
  }

  public List annotation;
  public List toc;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
