/* Generated By:JJTree: Do not edit this line. WikiParagraph.java */

package org.seasar.cms.wiki.parser;

public class WikiParagraph extends SimpleNode {
  public WikiParagraph(int id) {
    super(id);
  }

  public WikiParagraph(WikiParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
