/* Generated By:JJTree: Do not edit this line. WikiAlias.java */

package org.seasar.cms.wiki.parser;

public class WikiAlias extends SimpleNode {
  public WikiAlias(int id) {
    super(id);
  }

  public WikiAlias(WikiParser p, int id) {
    super(p, id);
  }
  
  public String image;
  public boolean islink = false;  


  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
