/* Generated By:JJTree: Do not edit this line. WikiListMember.java */

package org.seasar.cms.wiki.parser;

public class WikiListMember extends SimpleNode {
  public WikiListMember(int id) {
    super(id);
  }

  public WikiListMember(WikiParser p, int id) {
    super(p, id);
  }

  public int level;
  public int type;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
