/* Generated By:JJTree: Do not edit this line. WikiInlinePlugin.java */

package org.seasar.cms.wiki.parser;

public class WikiInlinePlugin extends SimpleNode {
  public WikiInlinePlugin(int id) {
    super(id);
  }

  public WikiInlinePlugin(WikiParser p, int id) {
    super(p, id);
  }

  public String name;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
