/* Generated By:JJTree: Do not edit this line. c:\workspace3\cms-wiki\src\main\java\org\seasar\cms\wiki\parser\WikiParserTreeConstants.java */

package org.seasar.cms.wiki.parser;

public interface WikiParserTreeConstants
{
  public int JJTSYNTAXERROR = 0;
  public int JJTSKIPTONEWLINE = 1;
  public int JJTGENERATETREE = 2;
  public int JJTVOID = 3;
  public int JJTPARAGRAPH = 4;
  public int JJTEXCERPT = 5;
  public int JJTLIST = 6;
  public int JJTLISTMEMBER = 7;
  public int JJTDEFINELIST = 8;
  public int JJTDEFINEDWORD = 9;
  public int JJTEXPLANATIONWORD = 10;
  public int JJTPRESHAPED = 11;
  public int JJTTABLE = 12;
  public int JJTTABLECOLUMN = 13;
  public int JJTTABLEMEMBER = 14;
  public int JJTCSVTABLE = 15;
  public int JJTHEADING = 16;
  public int JJTALIGN = 17;
  public int JJTFLOATALIGN = 18;
  public int JJTHORIZONTALLINE = 19;
  public int JJTBLOCKPLUGIN = 20;
  public int JJTLETTERS = 21;
  public int JJTANYOTHER = 22;
  public int JJTSTRONGITALIC = 23;
  public int JJTDELETELINE = 24;
  public int JJTANNOTATION = 25;
  public int JJTINTERWIKI = 26;
  public int JJTLINK = 27;
  public int JJTALIAS = 28;
  public int JJTPAGENAME = 29;
  public int JJTINLINEPLUGIN = 30;
  public int JJTARGS = 31;
  public int JJTERRORS = 32;


  public String[] jjtNodeName = {
    "SyntaxError",
    "SkipToNewline",
    "GenerateTree",
    "void",
    "Paragraph",
    "Excerpt",
    "List",
    "ListMember",
    "DefineList",
    "DefinedWord",
    "ExplanationWord",
    "Preshaped",
    "Table",
    "Tablecolumn",
    "Tablemember",
    "CSVTable",
    "Heading",
    "Align",
    "FloatAlign",
    "Horizontalline",
    "BlockPlugin",
    "Letters",
    "AnyOther",
    "StrongItalic",
    "Deleteline",
    "Annotation",
    "Interwiki",
    "Link",
    "Alias",
    "Pagename",
    "InlinePlugin",
    "Args",
    "Errors",
  };
}
