/* Generated By:JJTree: Do not edit this line. WikiDefineList.java */

package org.seasar.cms.wiki.parser;

public class WikiDefineList extends SimpleNode {
  public WikiDefineList(int id) {
    super(id);
  }

  public WikiDefineList(WikiParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
