/* Generated By:JJTree: Do not edit this line. WikiTable.java */

package org.seasar.cms.wiki.parser;

public class WikiTable extends SimpleNode {
  public WikiTable(int id) {
    super(id);
  }

  public WikiTable(WikiParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
