/* Generated By:JJTree: Do not edit this line. WikiLink.java */

package org.seasar.cms.wiki.parser;

public class WikiLink extends SimpleNode {
  public WikiLink(int id) {
    super(id);
  }

  public WikiLink(WikiParser p, int id) {
    super(p, id);
  }

  public String image;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
