/* Generated By:JJTree: Do not edit this line. WikiStrongItalic.java */

package org.seasar.cms.wiki.parser;

public class WikiStrongItalic extends SimpleNode {
  public WikiStrongItalic(int id) {
    super(id);
  }

  public WikiStrongItalic(WikiParser p, int id) {
    super(p, id);
  }
  
  public int prelevel;
  public int postlevel;

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
