/* Generated By:JJTree: Do not edit this line. WikiLetters.java */

package org.seasar.cms.wiki.parser;

public class WikiLetters extends SimpleNode {
  public WikiLetters(int id) {
    super(id);
  }

  public WikiLetters(WikiParser p, int id) {
    super(p, id);
  }

  public String letter;
  public boolean isURL = false;
  public boolean isEmail = false;
  public boolean isWikiname = false;
  public boolean isAnchor = false;
  public boolean isHTMLescape = false;
  public boolean isNewline = false;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
