/* Generated By:JJTree: Do not edit this line. WikiBlockPlugin.java */

package org.seasar.cms.wiki.parser;

public class WikiBlockPlugin extends SimpleNode {
  public WikiBlockPlugin(int id) {
    super(id);
  }

  public WikiBlockPlugin(WikiParser p, int id) {
    super(p, id);
  }

  public String name;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
