/* Generated By:JJTree: Do not edit this line. WikiErrors.java */

package org.seasar.cms.wiki.parser;

public class WikiErrors extends SimpleNode {
  public WikiErrors(int id) {
    super(id);
  }

  public WikiErrors(WikiParser p, int id) {
    super(p, id);
  }

  public String letter;  

  /** Accept the visitor. **/
  public Object jjtAccept(WikiParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
